development:
  adapter: postgresql
  database: convideumamulher
  user: gdutra
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: convideumamulher
  user: gdutra
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: convideumamulher
  user: gdutra
  pool: 5
  timeout: 5000
